(define (problem aeroport)
    (:domain aeroport)
    (:objects o1 o2 o3 o4 o5 av1 av2 bmb1 bmb3 c1 c2 c3 c5 )
    (:init (om o1) (om o2) (om o3) (om o4) (om o5)
            (avion av1) (avion av2)
            (bomba o1 bmb1)
            (cazier o1 c1)
            (cazier o2 c2)
            (cazier o3 c3)
            (bomba o3 bmb3)
            (cazier o5 c5)
            )
    (:goal (and(aresteaza o1)
            (calatorie o2)
            (suspect o2)
            (aresteaza o3)
            (calatorie o4)
            (calatorie o5))
    )
    )